version: '3.8'
services:
  user-service:
    container_name: user-service
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3005:3005"
    volumes:
      - ./backend/user-service:/api 
    env_file:
      - .env
    depends_on:
      - db-user  # Garante que o banco de dados inicie antes do user-service

  db-user:
    container_name: db_user
    build:
      context: ./backend/user-service/db
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - db_user:/var/lib/postgresql/data
      - ./backend/user-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Monta o script SQL inicial
    ports:
      - "5435:5432"

volumes:
  db_user:
