services:
  # api gateway -------------------------------- 
  api-gateway:
    container_name: api-gateway
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3005:3005"
    volumes:
      - ./backend/api-gateway:/api 
    depends_on:
      - db-gateway
    env_file:
      - ./backend/api-gateway/.env
  # user service -------------------------------- 
  user-service:
    container_name: user-service
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3006:3006"
    volumes:
      - ./backend/user-service:/api 
    depends_on:
      - db-gateway
    env_file:
      - ./backend/user-service/.env
  db-user:
    container_name: db-gateway
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    ports:
      - "5437:5432"
    volumes:
      -  db_user:/var/lib/postgresql/data
    restart: always
  # # admin service -------------------------------- 
  # admin-service:
  #   container_name: admin-service
  #   build:
  #     context: ./backend/admin-service
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "3008:3008"
  #   volumes:
  #     - ./backend/admin-service:/api 
  #   depends_on:
  #     - db-gateway
  #   env_file:
  #     - ./backend/admin-service/.env
  # db-admin:
  #   container_name: db-gateway
  #   build:
  #     context: ./backend/admin-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5435:5432"
  #   volumes:
  #     -  db_admin:/var/lib/postgresql/data
  #   restart: always
  # # admin service -------------------------------- 
  # game-service:
  #   container_name: game-service
  #   build:
  #     context: ./backend/game-service
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "3005:3005"
  #   volumes:
  #     - ./backend/game-service:/api 
  #   depends_on:
  #     - db-gateway
  #   env_file:
  #     - ./backend/game-service/.env
  # db-game:
  #   container_name: db-gateway
  #   build:
  #     context: ./backend/game-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5435:5432"
  #   volumes:
  #     -  db_game:/var/lib/postgresql/data
  #   restart: always
  
volumes:
  db_volume-gateway: