services:
  user-service:
    container_name: user-service
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3005:3005"
    volumes:
      - ./backend/user-service:/api 
    env_file:
      - .env
  db-user:
    container_name: db_user
    build:
      context: ./backend/user-service/db
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - db_user:/var/lib/postgresql/data
    ports:
      - "5435:5432"
  
volumes:
  db_user: